# Generated by Django 4.0.1 on 2022-01-31 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Type name', max_length=40, verbose_name="Author's name")),
                ('last_name', models.CharField(help_text='Type surname', max_length=30, verbose_name="Author's surname")),
                ('date_of_birth', models.DateField(blank=True, help_text='Type date of birth', null=True, verbose_name='Date of birth')),
                ('date_of_death', models.DateField(blank=True, help_text='Type date of death', null=True, verbose_name='Date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insert genre', max_length=40, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type the language', max_length=30, verbose_name='Book languauge')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Type title of the book', max_length=100, verbose_name='Title of the book')),
                ('summary', models.CharField(help_text='Brief summary', max_length=1000, verbose_name='Annotation')),
                ('isbn', models.CharField(help_text='Should contain 13 charaters', max_length=13, verbose_name='ISBN book')),
                ('author', models.ManyToManyField(help_text='Choose the author', null=True, to='catalog.Author', verbose_name='Author of the book')),
                ('genre', models.ForeignKey(help_text='Genre of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Genre')),
                ('language', models.ForeignKey(help_text='Choose the language', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Language')),
            ],
        ),
    ]
