# Generated by Django 4.0.1 on 2022-02-02 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Type inventar nomer', max_length=20, null=True, verbose_name='Inventar nomer')),
                ('imprint', models.CharField(help_text='Publisher and year', max_length=50, verbose_name='Publisher')),
                ('status', models.CharField(choices=[('a', 'available'), ('r', 'reserved'), ('s', 'sold')], help_text='Book availability', max_length=1, null=True, verbose_name='dgdfg')),
                ('due_back', models.DateField(blank=True, help_text='Input the end of the period', null=True, verbose_name='End date of the status')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
            ],
        ),
    ]
